[build]
  # Build command for Netlify
  command = "npm run build:netlify"
  
  # Directory to publish (where the built files are)
  publish = "dist/public"
  
  # Functions directory (if you want to use Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build environment
  NODE_ENV = "production"
  
  # Enable build plugins
  NETLIFY_USE_YARN = "false"

# Redirect rules for SPA routing
# If your backend is external, rely on client/public/_redirects instead.

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (if needed)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Edge functions (optional, for advanced use cases)
# [[edge_functions]]
#   function = "hello"
#   path = "/api/hello"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.8

# Branch-specific settings
[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"

[context.branch-deploy]
  command = "npm run build:netlify"
