services:
  - type: web
    name: nftsol
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nftsol-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SOLANA_NETWORK
        value: devnet
      - key: PORT
        value: 3001

databases:
  - name: nftsol-db
    databaseName: nftsol
    plan: free
    region: oregon
