# NFTSol Client Environment Setup Script
# This script sets up client-side environment variables securely

Write-Host "🔧 Setting up NFTSol client environment..." -ForegroundColor Green

# Check if we're in the client directory
if (-not (Test-Path "package.json")) {
    Write-Host "❌ This script must be run from the client directory" -ForegroundColor Red
    exit 1
}

# Create .env.local file if it doesn't exist
$envFile = ".env.local"
if (-not (Test-Path $envFile)) {
    Write-Host "📝 Creating .env.local file..." -ForegroundColor Yellow
    
    $envContent = @"
# NFTSol Client Environment Configuration
# Generated by setup-client-env.ps1

# API Configuration
VITE_API_BASE=http://localhost:3000

# Environment Configuration
VITE_NODE_ENV=development

# Wallet Configuration
VITE_SOLANA_CLUSTER=devnet

# Feature Flags
VITE_ENABLE_ANALYTICS=false
VITE_ENABLE_DEBUG=true
VITE_ENABLE_MOCK_DATA=false

# External Services
VITE_IPFS_GATEWAY=https://gateway.pinata.cloud
VITE_SOLANA_RPC_URL=https://api.devnet.solana.com
"@
    
    $envContent | Out-File -FilePath $envFile -Encoding UTF8
    Write-Host "✅ Created .env.local file" -ForegroundColor Green
} else {
    Write-Host "✅ .env.local file already exists" -ForegroundColor Green
}

# Validate environment variables
Write-Host "🔍 Validating client environment..." -ForegroundColor Cyan

# Check if VITE_API_BASE is set
if ($env:VITE_API_BASE) {
    Write-Host "✅ VITE_API_BASE: $env:VITE_API_BASE" -ForegroundColor Green
} else {
    Write-Host "⚠️ VITE_API_BASE not set, using default: http://localhost:3000" -ForegroundColor Yellow
}

# Check if VITE_SOLANA_CLUSTER is set
if ($env:VITE_SOLANA_CLUSTER) {
    Write-Host "✅ VITE_SOLANA_CLUSTER: $env:VITE_SOLANA_CLUSTER" -ForegroundColor Green
} else {
    Write-Host "⚠️ VITE_SOLANA_CLUSTER not set, using default: devnet" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "🎉 Client environment setup complete!" -ForegroundColor Cyan
Write-Host "🔒 All client configuration is secure and environment-specific" -ForegroundColor Green
Write-Host ""
Write-Host "🚀 Ready to start client development:" -ForegroundColor Green
Write-Host "   npm run dev" -ForegroundColor White
